[project]
name = "final-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SebL2", email = "68055840+SebL2@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
final-service = "final_service:main"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"
